apiVersion: v1
kind: Service
metadata:
  name: {{ include "contributr.fullname" . }}-backend
  labels:
    {{- include "contributr.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: {{ .Release.Namespace }}-{{ include "contributr.fullname" . }}-backend-transport@kubernetescrd
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "contributr.selectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
