apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contributr.fullname" . }}-frontend
  labels:
    {{- include "contributr.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
data:
  API_URL: "http://{{ include "contributr.fullname" . }}-backend:8000/api"
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
