apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contributr.fullname" . }}-backend
  labels:
    {{- include "contributr.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
data:
  RUN_MIGRATIONS: {{ .Values.backend.runMigrations | quote }}
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.backend.jwtAccessTokenExpireMinutes | quote }}
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: {{ .Values.backend.jwtRefreshTokenExpireDays | quote }}
  {{- $scheme := ternary "https" "http" .Values.ingress.tls.enabled }}
  BACKEND_CORS_ORIGINS: '[{{ printf "%s://%s" $scheme .Values.ingress.host | quote }}]'
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
