apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contributr.fullname" . }}-redis
  labels:
    {{- include "contributr.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "contributr.selectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "contributr.componentLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "contributr.image" (dict "root" . "repository" .Values.redis.image.repository "tag" .Values.redis.image.tag) }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: tcp-redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
