import type { DateRange } from "@/components/date-range-filter";

export const queryKeys = {
  projects: {
    all: ["projects"] as const,
    detail: (id: string) => ["projects", id] as const,
    stats: (id: string, range?: { from?: string; to?: string }) => ["projects", id, "stats", range] as const,
    prStats: (id: string) => ["projects", id, "prStats"] as const,
  },
  repos: {
    detail: (id: string) => ["repos", id] as const,
    stats: (id: string, filters?: { branches?: string[]; from?: string; to?: string }) => ["repos", id, "stats", filters] as const,
    syncJobs: (id: string) => ["repos", id, "syncJobs"] as const,
    branches: (id: string, contributorId?: string) => ["repos", id, "branches", contributorId] as const,
    contributors: (id: string, branches?: string[]) => ["repos", id, "contributors", branches] as const,
    fileTree: (id: string, branch?: string) => ["repos", id, "fileTree", branch] as const,
    hotspots: (id: string, branch?: string) => ["repos", id, "hotspots", branch] as const,
    fileDetail: (id: string, path: string, branch?: string) => ["repos", id, "files", path, branch] as const,
    commits: (id: string, filters?: Record<string, unknown>) => ["repos", id, "commits", filters] as const,
  },
  contributors: {
    all: (projectId?: string) => ["contributors", { projectId }] as const,
    duplicates: ["contributors", "duplicates"] as const,
    detail: (id: string) => ["contributors", id] as const,
    stats: (id: string, filters?: Record<string, unknown>) => ["contributors", id, "stats", filters] as const,
    repos: (id: string) => ["contributors", id, "repos"] as const,
    commits: (id: string, filters?: Record<string, unknown>) => ["contributors", id, "commits", filters] as const,
  },
  daily: (params: Record<string, unknown>) => ["dailyStats", params] as const,
  trends: (params: Record<string, unknown>) => ["trends", params] as const,
  sshKeys: ["sshKeys"] as const,
  platformCredentials: ["platformCredentials"] as const,
  users: ["users"] as const,
  fileExclusions: ["fileExclusions"] as const,
  aiSettings: ["aiSettings"] as const,
  aiStatus: ["aiStatus"] as const,
  llmProviders: ["llmProviders"] as const,
  agents: ["agents"] as const,
  agentDetail: (slug: string) => ["agents", slug] as const,
  aiTools: ["aiTools"] as const,
  knowledgeGraphs: ["knowledgeGraphs"] as const,
  knowledgeGraphDetail: (id: string) => ["knowledgeGraphs", id] as const,
  commitDetail: (id: string) => ["commitDetail", id] as const,
};
